name: Notify Telegram on PR
on:
  pull_request:
    types: [opened, closed]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send message to Telegram
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
        -d chat_id=$CHAT_ID \
        -d text="New PR created: ${{ github.event.pull_request.html_url }}"
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
